# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: black (python)
        args: [--line-length=88]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        name: shfmt (shell)
        # These follow lint.sh from pwndbg
        args: ["-i", "4", "-bn", "-ci", "-sr"]
  - repo: https://github.com/netromdk/vermin
    rev: "v1.5.2"
    hooks:
      - id: vermin
        name: vermin (python)
        args: ["-t=3.8-", "--violations", "--no-tips", "-vvvv"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.291
    hooks:
      - id: ruff
        name: ruff (python)
        args:
          # Ignore E501 (line too long) and E402 (module level import not at top
          # of file), because of tracing. F821 because of how we use log
          ["--fix", "--ignore", "E501", "--ignore", "E402", "--ignore", "F821"]
